# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_2 || ORIG_REF_NAME==design_1_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_kappa_mul_k_0_0/design_1_kappa_mul_k_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_kappa_mul_k_0_0 || ORIG_REF_NAME==design_1_kappa_mul_k_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cordic_0_1/design_1_cordic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cordic_0_1 || ORIG_REF_NAME==design_1_cordic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mul_kappa_0_0/design_1_mul_kappa_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mul_kappa_0_0 || ORIG_REF_NAME==design_1_mul_kappa_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dist_init_0_0/design_1_dist_init_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dist_init_0_0 || ORIG_REF_NAME==design_1_dist_init_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sph2cas_0_0/design_1_sph2cas_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sph2cas_0_0 || ORIG_REF_NAME==design_1_sph2cas_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cas2bufa_0_0/design_1_cas2bufa_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cas2bufa_0_0 || ORIG_REF_NAME==design_1_cas2bufa_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cordic_1_0/design_1_cordic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cordic_1_0 || ORIG_REF_NAME==design_1_cordic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cordic_1_1/design_1_cordic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cordic_1_1 || ORIG_REF_NAME==design_1_cordic_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cordic_1_2/design_1_cordic_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cordic_1_2 || ORIG_REF_NAME==design_1_cordic_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cordic_1_3/design_1_cordic_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cordic_1_3 || ORIG_REF_NAME==design_1_cordic_1_3} -quiet] -quiet

# XDC: c:/Users/guan/Desktop/pynq_project/exponential/exponential.gen/sources_1/bd/design_1/design_1_ooc.xdc
